import { checkUser, signUp, loGin, updateUser, listArticle, getProfile, getUser, showUser, newUser, getArticle, createCmt, getComment, listTag, favorArt } from './init'
import { newArt, newTag, editArt, checkPage, delArt, feedArt, followUser, unfollowUser, logOut } from './article'
window.addEventListener('DOMContentLoaded', function () {
  signUp()
  checkUser()
  loGin()
  updateUser()
  listArticle()
  getProfile()
  getUser()
  showUser()
  newUser()
  getArticle()
  createCmt()
  getComment()
  newArt()
  newTag()
  editArt()
  checkPage()
  delArt()
  feedArt()
  followUser()
  unfollowUser()
  listTag()
  favorArt()
  logOut()
})
